import type { Metadata } from "next";
import "./globals.css";
import "../stylesheets/antdOverride.css";
import "../stylesheets/commonClasses.css";
import "../stylesheets/layout.css";
import LayoutProvider from "@/components/LayoutProvider";

export const metadata: Metadata = {
  title: "APS-Jobs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <LayoutProvider>{children}</LayoutProvider>;
}
